# Use an official Python 3.9 image as a base
FROM python:3.12-slim

WORKDIR /tmp
COPY requirements.txt /tmp/

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt



# Set the working directory to /app
WORKDIR /app

# Copy the source files file
COPY server server


EXPOSE 8091

# Run the command to start the app when the container starts
CMD ["python", "-m", "server.backApp" ]
