
services:
  storage_tools_server:
    build:
      context: .
      network: host
    image: storage_tools_server
    container_name: storage_tools_server
    network_mode: host
    volumes:
      - ${UPLOAD_DIR}:/mnt/uploads
    tty: true
    stdin_open: true
    restart: always
