#
# Storage Tools Config file 
# 

# ----------------------------------------------
# Required updates
# ----------------------------------------------



# production should just be "/"
volume_root: "/"


blackout:
 - /volume3/chiron/datasets/experiments/20240610_je_backup
 - je_backup/blue_orin_data_james_20240610
 - /volume4/dsta/datasets/match_anything/
 - /volume4/dsta/datasets/ego-exo4d/
 - /volume4/dsta/datasets/old-autel-project-datasets
 

# ----------------------------------------------
# Optional updates
# ----------------------------------------------

# The port that the server will run on
port: 8091

# How many parallel processing threads to run per connection at a time. 
threads: 4

# Preloads the database with project, robot names and sites.
# This is optional because the Config interface will allow 
# for the addition of new entries. 
projects:
 - chiron
 - dsta

robots:
 - RC_car
 - wheelchair
 - spot

sites:
 - data_workshop
 - sqi
 - shelter


# what kinds of files to search for
# when importing directly.   
include_suffix:
  - mcap
  - mp4 
  - txt
  - bag 
  - ass
  - yaml
#  - png # not using PNG because there are just too many, and this
         # isn't the right way to browse images right now.  



# ----------------------------------------------
# Server Optional updates
# ----------------------------------------------


# set to true for production server
# set to false for local or field server. 
use_ldap: true

# ----------------------------------------------
# Remote mode configuration
# ----------------------------------------------

# Look for the main servers at these address
# Can be a host name, or a remote tunnel
# Uncomment when running this server in the field
# or when syncing with main server

# remote:
#   - "airlab-share-01.andrew.cmu.edu:8091"
#   - "localhost:8092"



