#
# Storage Tools Config file 
# 

# ----------------------------------------------
# Required updates
# ----------------------------------------------


# Set the upload_dir to a path that is read/write for
# the user running the server.  
# When running as Docker, make sure the docker user
# has read/write permissions for the directory

upload_dir: "/mnt/uploads/"

# The volume_root is a prefix that is added to volume mapping entry 
# for a given project. This allows each project to go into a different
# directory, or different mounted location.  
# The volume_root does not have to be the same as the upload_dir.  
volume_root: "/mnt/uploads/"

# ----------------------------------------------
# Optional updates
# ----------------------------------------------

# The port that the server will run on
port: 8091

# How many parallel processing threads to run per connection at a time. 
threads: 4

# Preloads the database with  project, robot names and sites.
# This is optional because the Config interface will allow 
# for the addition of new entries. 

robots:
 - RC_car
 - wheelchair
 - spot

sites:
 - data_workshop
 - sqi
 - shelter


# what kinds of files to search for
# when importing directly.   
include_suffix:
  - mcap
  - mp4 
  - txt
  - bag 
  - ass
  - yaml
#  - png # not using PNG because there are just too many, and this
         # isn't the right way to browse images right now.  



# set to true for production server
# set to false for local or field server. 
use_ldap: true

# ----------------------------------------------
# Remote mode configuration
# ----------------------------------------------

# Look for the main servers at these address
# Can be a host name, or a remote tunnel
# Uncomment when running this server in the field
# or when syncing with main server

#remote:
#  - "airlab-storage.andrew.cmu.edu:8091"
#   - "localhost:8092"

# The server key to use when acting as remote
# uncomment the next line and set it to the 
# correct API key.  

API_KEY_TOKEN: "server_1_key_asfaa9"





# # how long to wait before checking again
# wait_s: 2
